# Generated by Django 5.1.4 on 2025-01-24 13:59

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, default='default/category_logo.png', null=True, upload_to=event.models.upload_location),
        ),
    ]
