# Generated by Django 5.1.4 on 2025-02-10 11:55

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(default='/default/category_logo.png', upload_to=event.models.upload_location),
        ),
    ]
