# Generated by Django 5.1.4 on 2025-02-13 12:18

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(default='default/default_category_logo.png', upload_to=event.models.upload_location),
        ),
    ]
